import asyncio
import threading
import requests
import logging
from datetime import datetime
from flask import Flask
from metaapi_cloud_sdk import MetaApi

META_TOKEN = "METAAPI_TOKENINGIZ"
ACCOUNT_ID = "METAAPI_ACCOUNT_ID"
BOT_TOKEN = "TELEGRAM_BOT_TOKENINGIZ"
CHAT_ID = "1920797472"

SYMBOL = "XAUUSDm"
LOT = 0.01
TP_POINTS = 4
MAX_TRADES = 1
INTERVAL = 290INTERVAL = 290

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(message)s")
log = logging.getLogger(__name__)

app = Flask(__name__)
bot_status = {"running": False, "last_check": "—", "last_signal": "—", "trades": 0}

@app.route("/")
def home():
    s = bot_status
        return f"<html><body style='background:#0a0e1a;color:#00e896;padding:30px'><h2>XAUUSD Bot</h2><p>Status: {'ISHLAYAPTI' if s['running'] else 'TOXTATILGAN'}</p><p>Tekshiruv: {s['last_check']}</p><p>Signal: {s['last_signal']}</p><p>Savdolar: {s['trades']}</p></body></html>"

        def run_flask():
            app.run(host="0.0.0.0", port=8080, use_reloader=False)

            def telegram(text):
                try:
                        requests.post(f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",
                                    json={"chat_id": CHAT_ID, "text": text, "parse_mode": "HTML"}, timeout=10)
                                        except Exception as e:
                                                log.error(f"Telegram: {e}")def get_candles(yf_interval, yf_range):
                                                    try:
                                                            url = f"https://query1.finance.yahoo.com/v8/finance/chart/GC=F?interval={yf_interval}&range={yf_range}"
                                                                    r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}, timeout=15)
                                                                            data = r.json()
                                                                                    chart = data["chart"]["result"][0]
                                                                                            ts = chart["timestamp"]
                                                                                                    q = chart["indicators"]["quote"][0]
                                                                                                            candles = []
                                                                                                                    for i in range(len(ts)):
                                                                                                                                o, c, h, l = q["open"][i], q["close"][i], q["high"][i], q["low"][i]
                                                                                                                                            if None in (o, c, h, l): continue
                                                                                                                                                        candles.append({"time": ts[i], "open": round(o,2), "close": round(c,2),
                                                                                                                                                                        "high": round(h,2), "low": round(l,2), "bull": c>=o,
                                                                                                                                                                                        "total_shadow": round(h-l,4)})
                                                                                                                                                                                                return candles[:-1] if len(candles) > 3 else None
                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                            log.error(f"Narx: {e}"); return None

                                                                                                                                                                                                            def detect_signal(candles):
                                                                                                                                                                                                                if len(candles) < 3: return None, 0, 0
                                                                                                                                                                                                                    c1, c2, c3 = candles[-3], candles[-2], candles[-1]
                                                                                                                                                                                                                        ok = c2["total_shadow"] > c1["total_shadow"]
                                                                                                                                                                                                                            if c1["bull"] and not c2["bull"] and not c3["bull"] and ok:
                                                                                                                                                                                                                                    return "SELL", c3["close"], c2["high"]
                                                                                                                                                                                                                                        if not c1["bull"] and c2["bull"] and c3["bull"] and ok:
                                                                                                                                                                                                                                                return "BUY", c3["close"], c2["low"]
                                                                                                                                                                                                                                                    return None, 0, 0async def place_order(conn, signal, entry, sl_price, tf_name):
                                                                                                                                                                                                                                                        tp = round(entry + TP_POINTS, 2) if signal=="BUY" else round(entry - TP_POINTS, 2)
                                                                                                                                                                                                                                                            sl = round(sl_price, 2)
                                                                                                                                                                                                                                                                sl_dist = round(abs(entry - sl), 2)
                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                            if signal == "BUY":
                                                                                                                                                                                                                                                                                        await conn.create_market_buy_order(SYMBOL, LOT, sl, tp, {"comment": f"ShadowBot_{tf_name}"})
                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                            await conn.create_market_sell_order(SYMBOL, LOT, sl, tp, {"comment": f"ShadowBot_{tf_name}"})
                                                                                                                                                                                                                                                                                                                    icon = "🟢" if signal=="BUY" else "🔴"
                                                                                                                                                                                                                                                                                                                            now = datetime.now().strftime("%d.%m.%Y %H:%M")
                                                                                                                                                                                                                                                                                                                                    telegram(f"{icon} <b>{signal} OCHILDI</b>\n\n📊 XAUUSD | ⏱ {now}\n🕐 <b>Tayfreym:</b> {tf_name}\n💰 <b>Kirish:</b> <code>{entry:.2f}</code>\n🎯 <b>TP:</b> <code>{tp:.2f}</code>\n🛡 <b>SL:</b> <code>{sl:.2f}</code> (soya uchi)\n📦 <b>Lot:</b> {LOT}")
                                                                                                                                                                                                                                                                                                                                            log.info(f"{signal} @ {entry} | TP:{tp} | SL:{sl} | {tf_name}")
                                                                                                                                                                                                                                                                                                                                                    return True
                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                log.error(f"Order: {e}"); telegram(f"⚠️ Order xatosi: {str(e)[:100]}"); return False

                                                                                                                                                                                                                                                                                                                                                                TIMEFRAMES = [
                                                                                                                                                                                                                                                                                                                                                                        {"name": "M5",  "yf_interval": "5m",  "yf_range": "1d",  "check_sec": 60},
                                                                                                                                                                                                                                                                                                                                                                            {"name": "M15", "yf_interval": "15m", "yf_range": "5d",  "check_sec": 120},
                                                                                                                                                                                                                                                                                                                                                                                {"name": "M30", "yf_interval": "30m", "yf_range": "5d",  "check_sec": 180},
                                                                                                                                                                                                                                                                                                                                                                                    {"name": "H1",  "yf_interval": "60m", "yf_range": "1mo", "check_sec": 300},
                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                ]async def timeframe_task(conn, tf):
                                                                                                                                                                                                                                                                                                                                                                    name = tf["name"]
                                                                                                                                                                                                                                                                                                                                                                        interval = tf["yf_interval"]
                                                                                                                                                                                                                                                                                                                                                                            yf_range = tf["yf_range"]
                                                                                                                                                                                                                                                                                                                                                                                check_sec = tf["check_sec"]
                                                                                                                                                                                                                                                                                                                                                                                    last_c_time = 0
                                                                                                                                                                                                                                                                                                                                                                                        while True:
                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                            candles = get_candles(interval, yf_range)
                                                                                                                                                                                                                                                                                                                                                                                                                        if candles:
                                                                                                                                                                                                                                                                                                                                                                                                                                        c_time = candles[-1]["time"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                        signal, entry, sl_price = detect_signal(candles)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if signal and c_time != last_c_time:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            last_c_time = c_time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot_status["last_signal"] = f"{name}: {signal} @ {entry:.2f}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    positions = await conn.get_positions()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        open_count = sum(1 for p in positions if p.get("symbol")==SYMBOL)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if open_count < MAX_TRADES:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ok = await place_order(conn, signal, entry, sl_price, name)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ok: bot_status["trades"] += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        telegram(f"ℹ️ [{name}] {signal} @ {entry:.2f} — pozitsiya band")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            log.info(f"[{name}] Signal yoq | {candles[-1]['close']:.2f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                log.error(f"[{name}] {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await asyncio.sleep(check_sec)async def bot_main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            telegram("⏳ <b>Bot</b> ishga tushmoqda...\nExness MT5 ga ulanilmoqda...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        api = MetaApi(META_TOKEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                account = await api.metatrader_account_api.get_account(ACCOUNT_ID)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if account.state != "DEPLOYED": await account.deploy()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await account.wait_connected()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn = account.get_rpc_connection()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await conn.connect()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await conn.wait_synchronized()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot_status["running"] = True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        telegram(f"✅ <b>Bot tayyor!</b>\n\nM5 · M15 · M30 · H1 kuzatilmoqda\n📦 Lot: {LOT} | 🎯 TP: +{TP_POINTS} punkt | 🛡 SL: soya uchi\n\nAvtomatik savdo boshlandi! 🚀")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tasks = [asyncio.create_task(timeframe_task(conn, tf)) for tf in TIMEFRAMES]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await asyncio.gather(*tasks)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    log.error(f"MetaAPI: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            telegram(f"❌ Ulanish xatosi: {str(e)[:150]}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                threading.Thread(target=run_flask, daemon=True).start()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    asyncio.run(bot_main())
